import { Property } from "@/types/property";

export const properties: Property[] = [
    {
        id: "1",
        title: "Luxurious Modern Villa",
        price: 1250000,
        location: "123 Palm Avenue, Beverly Hills",
        city: "Beverly Hills",
        bedrooms: 5,
        bathrooms: 4,
        area: 4200,
        image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
        type: "sale",
        propertyType: "villa",
        featured: true,
        description: "Stunning modern villa with panoramic views, infinity pool, and smart home technology throughout.",
        amenities: ["Pool", "Gym", "Garden", "Smart Home", "Garage"],
        yearBuilt: 2022,
        agent: { name: "Sarah Mitchell", phone: "+1 310-555-0142", image: "" },
    },
    {
        id: "2",
        title: "Downtown Penthouse Suite",
        price: 8500,
        location: "456 Skyline Blvd, Manhattan",
        city: "New York",
        bedrooms: 3,
        bathrooms: 2,
        area: 2100,
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
        type: "rent",
        propertyType: "apartment",
        featured: true,
        description: "Breathtaking penthouse with floor-to-ceiling windows and unobstructed city views.",
        amenities: ["Doorman", "Rooftop", "Gym", "Concierge"],
        yearBuilt: 2020,
        agent: { name: "James Rodriguez", phone: "+1 212-555-0198", image: "" },
    },
    {
        id: "3",
        title: "Charming Coastal Cottage",
        price: 685000,
        location: "789 Ocean Drive, Malibu",
        city: "Malibu",
        bedrooms: 3,
        bathrooms: 2,
        area: 1800,
        image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
        type: "sale",
        propertyType: "house",
        featured: true,
        description: "Beautiful beachfront cottage just steps from the sand. Perfect weekend retreat.",
        amenities: ["Beach Access", "Deck", "Fireplace", "Garden"],
        yearBuilt: 2018,
        agent: { name: "Emily Chen", phone: "+1 424-555-0167", image: "" },
    },
    {
        id: "4",
        title: "Urban Loft Living",
        price: 3200,
        location: "321 Art District, Chicago",
        city: "Chicago",
        bedrooms: 2,
        bathrooms: 1,
        area: 1400,
        image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
        type: "rent",
        propertyType: "apartment",
        featured: false,
        description: "Industrial-chic loft with exposed brick, high ceilings, and modern finishes.",
        amenities: ["Rooftop", "Laundry", "Bike Storage", "Pet Friendly"],
        yearBuilt: 2019,
        agent: { name: "Michael Park", phone: "+1 312-555-0134", image: "" },
    },
    {
        id: "5",
        title: "Elegant Suburban Estate",
        price: 2100000,
        location: "567 Heritage Lane, Greenwich",
        city: "Greenwich",
        bedrooms: 6,
        bathrooms: 5,
        area: 6500,
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        type: "sale",
        propertyType: "house",
        featured: true,
        description: "Magnificent estate on 3 acres with tennis court, pool house, and manicured gardens.",
        amenities: ["Pool", "Tennis Court", "Wine Cellar", "Home Theater", "Guest House"],
        yearBuilt: 2021,
        agent: { name: "Victoria Adams", phone: "+1 203-555-0189", image: "" },
    },
    {
        id: "6",
        title: "Sleek City Condo",
        price: 475000,
        location: "890 Metro Square, Austin",
        city: "Austin",
        bedrooms: 2,
        bathrooms: 2,
        area: 1200,
        image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
        type: "sale",
        propertyType: "condo",
        featured: false,
        description: "Modern condo in the heart of downtown with balcony views and premium amenities.",
        amenities: ["Pool", "Gym", "Concierge", "Parking"],
        yearBuilt: 2023,
        agent: { name: "David Kim", phone: "+1 512-555-0156", image: "" },
    },
    {
        id: "7",
        title: "Mediterranean Townhouse",
        price: 890000,
        location: "234 Sunset Terrace, Miami",
        city: "Miami",
        bedrooms: 4,
        bathrooms: 3,
        area: 2800,
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        type: "sale",
        propertyType: "townhouse",
        featured: false,
        description: "Gorgeous Mediterranean-style townhouse with private courtyard and rooftop terrace.",
        amenities: ["Courtyard", "Rooftop", "Pool", "Smart Home"],
        yearBuilt: 2020,
        agent: { name: "Isabella Torres", phone: "+1 305-555-0178", image: "" },
    },
    {
        id: "8",
        title: "Mountain View Retreat",
        price: 4500,
        location: "678 Alpine Road, Denver",
        city: "Denver",
        bedrooms: 3,
        bathrooms: 2,
        area: 2200,
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
        type: "rent",
        propertyType: "house",
        featured: false,
        description: "Stunning mountain retreat with wraparound deck and panoramic Rocky Mountain views.",
        amenities: ["Fireplace", "Deck", "Hot Tub", "Hiking Trails"],
        yearBuilt: 2017,
        agent: { name: "Robert Hayes", phone: "+1 720-555-0145", image: "" },
    },
];

